### ISSUE TITLE
peerDependency hell

### ISSUE THREAD

**Issue by rolfl** [ajv-validator/ajv-draft-04#3]
I have a relatively complicated enterprise environment where I am writing some reusable code in my own library, which in turn has multiple dependencies, with multiple places that use AJV. One in particular is @seriousme/openapi-schema-validator - which has the following "simple" dependencies: https://github.com/seriousme/openapi-schema-validator/blob/master/package.json#L10

```json
  "dependencies": {
    "ajv": "^8.6.0",
    "ajv-draft-04": "^1.0.0",
    "js-yaml": "^4.1.0"
  }
```

When launching an application using my library, though, I get the following error:

```text
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'ajv/dist/core'
Require stack:
- /home/rolf/bmix/myapp/node_modules/ajv-draft-04/dist/index.js
- /home/rolf/bmix/myapp/node_modules/@seriousme/openapi-schema-validator/index.js
- /home/rolf/bmix/myapp/node_modules/fastify-openapi-glue/lib/parser.js
- /home/rolf/bmix/myapp/node_modules/fastify-openapi-glue/index.js
```

It's quite clear, that AJV 8.6.0 has `ajv/dist/core`, though, BUT, even though both:
- ajv-draft-04 has a peerDependency of AJV 8.5.0
- my own library requires AJV 8.6.0 for other reasons.

what happens is that NPM install "trampolines" `ajv-draft-04` to the top-level `node_modules` of the application. Both my library and the @seriousme/openapi-schema-validator libraries have AJV 8.6.0 in their "local" `node_modules`. The actual version of the top-level `node_modules` is 6.12.6 - NPM chooses to de-dup that version, instead of 8.6.0... The tail-end of the `npm-ls` looks like:

```text
├─┬ eslint@7.29.0
│ ├─┬ @eslint/eslintrc@0.4.2
│ │ └── ajv@6.12.6  deduped
│ ├── ajv@6.12.6 
│ └─┬ table@6.7.1
│   └── ajv@8.6.0 
└─┬ fastify@3.18.0
  ├─┬ @fastify/ajv-compiler@1.1.0
  │ └── ajv@6.12.6  deduped
  ├─┬ fast-json-stringify@2.7.7
  │ └── ajv@6.12.6  deduped
  └─┬ light-my-request@4.4.1
    └── ajv@6.12.6  deduped
```

The end result of this is that `ajv-draft-04` and `ajv` version `6.12.6` are both at the top-level `node-modules`, and that AJV version is not compatible.

I am not sure what to recommend, but, it appears, at this moment, that I have to force dozens of applications to require AJV 8.6.0 at their top level to prevent the `dedup` of the wrong version of AJV.

Note, running `npm --version` version `6.14.11` - I see there's a change in peerDependency handling with npm 7.... as an enterprise, we are slow to move to version, but will try npm 7

**Comment by rolfl** [comment]
With NPM version 7.x it appears the new peerDependency handling (force-loading peerDependencies instead of ignoring them) changes the behaviour see: https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies :

```text
│ └─┬ fastify-openapi-glue@2.6.2
│   ├─┬ @seriousme/openapi-schema-validator@1.2.0
│   │ ├─┬ ajv-draft-04@1.0.0
│   │ │ └── ajv@8.6.0 deduped
│   │ └── ajv@8.6.0
│   ├─┬ ajv-formats@2.1.0
│   │ └── ajv@8.6.0
│   └── ajv@8.6.0
├─┬ eslint@7.29.0
│ ├─┬ @eslint/eslintrc@0.4.2
│ │ └── ajv@6.12.6
│ ├── ajv@6.12.6
│ └─┬ table@6.7.1
│   └── ajv@8.6.0
└─┬ fastify@3.18.0
  ├─┬ @fastify/ajv-compiler@1.1.0
  │ └── ajv@6.12.6
  ├─┬ fast-json-stringify@2.7.7
  │ └── ajv@6.12.6
  └─┬ light-my-request@4.4.1
    └── ajv@6.12.6
```

Humph... closing this, but pleased to have recorded this so maybe someone else can be saved a few hours of debugging.

Note that npm 7 with `--legacy-peer-deps` option does things differently again, the install runs CLEAN (NO ERRORS OR WARNINGS), but `npm ls ajv` shows:
```
│ └─┬ fastify-openapi-glue@2.6.2
│   ├─┬ @seriousme/openapi-schema-validator@1.2.0
│   │ ├─┬ ajv-draft-04@1.0.0
│   │ │ └── ajv@7.2.4 deduped invalid: "^8.5.0" from node_modules/ajv-draft-04
│   │ └── ajv@8.6.0
│   ├─┬ ajv-formats@2.1.0
│   │ └── ajv@8.6.0
│   └── ajv@8.6.0
```

Running the application fails with:

```text
/home/rolf/bmix/myapp/node_modules/ajv-draft-04/dist/vocabulary/draft4.js:11
    applicator_1.default(),
                        ^

TypeError: applicator_1.default is not a function
    at Object.<anonymous> (/home/rolf/bmix/myapp/node_modules/ajv-draft-04/dist/vocabulary/draft4.js:11:25)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```
