### ISSUE TITLE
Error: Schema with key or id already exists

### ISSUE THREAD

**Issue by jeremyfiel** [ajv-validator/ajv-draft-04#7]
```sh
├── ajv-draft-04@1.0.0
├── ajv@8.11.0
```
```js
const Ajv = require('ajv-draft-04')
const ajvJson4Schema = require('../schemas/json-schema-draft-04.json')


let _ajvOptions = {
    strict: false,
    strictSchema: true,
    strictTypes: true,
    verbose: true,
    allErrors: true
}

let _draft4Validator = null

```

```js
   let schema = {
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "ActivityLogs",
	"description": "Activity Logs for a specific associate",
	"type": "object",
	"properties": {
		"activityLog": {
                    "type": "string"
                 }
         }
   }

    let results

    try {

        if (_draft4Validator == null) {
            let ajv = new Ajv(_ajvOptions)

            _draft4Validator = ajv.compile(ajvJson4Schema)
        }

        let valid = _draft4Validator(schema)

        results = {
            valid: valid,
            error: _draft4Validator.errors
        }

    } catch (err) {
        results = {
            valid: false,
            error: err
        }
    }
```

```sh
$ node index.js 
{
  valid: false,
  Exception has occurred: Error: schema with key or id "http://json-schema.org/draft-04/schema" already exists
  at Ajv._checkUnique (c:\Users\fieljere\ajvtest\node_modules\ajv\dist\core.js:465:19)
    at Ajv._addSchema (c:\Users\fieljere\ajvtest\node_modules\ajv\dist\core.js:456:22)
    at Ajv.compile (c:\Users\fieljere\ajvtest\node_modules\ajv\dist\core.js:158:26)
    at Object.<anonymous> (c:\Users\fieljere\ajvtest\index.js:34:28)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

I'm trying to import this package into the latest version of ajv and when I execute it, i'm receiving an error for `schema key or id already exists` 
I don't have `id` used in all of my schemas and even when it is present, with different values, the error persists.  

Can you please help me with this error? 

Thanks so much!

**Comment by jeremyfiel** [comment]
i found this `TODO` where i'm having the exception called.

https://github.com/ajv-validator/ajv/blob/b3e0cb17d0e095b5c883042b2306571be5ec86b7/lib/core.ts#L717

**Comment by GheorgheP** [comment]
@jeremyfiel, I'm having the same problem. How did you fix it?

**Comment by jeremyfiel** [comment]
share your schema and code and i'll try to help you
